// Auto-generated by scripts/generate-build-info.mjs — DO NOT EDIT.
// Wird bei jedem 'npm run dev' und 'npm run build' regeneriert.
export const BUILD_INFO = {
  "version": "0.828",
  "sha": "ffccdb3",
  "branch": "main",
  "buildAt": "2026-06-05T15:19:11.333Z",
  "files": 342,
  "lines": 50650,
  "words": 204119
} as const;
