// Auto-generated by scripts/generate-build-info.mjs — DO NOT EDIT.
// Wird bei jedem 'npm run dev' und 'npm run build' regeneriert.
export const BUILD_INFO = {
  "version": "0.940",
  "sha": "1e2ffc7",
  "branch": "main",
  "buildAt": "2026-06-13T14:15:01.584Z",
  "files": 405,
  "lines": 61272,
  "words": 249073
} as const;
