// Auto-generated by scripts/generate-build-info.mjs — DO NOT EDIT.
// Wird bei jedem 'npm run dev' und 'npm run build' regeneriert.
export const BUILD_INFO = {
  "version": "0.738",
  "sha": "f1dbe96",
  "branch": "main",
  "buildAt": "2026-05-12T07:56:04.945Z",
  "files": 282,
  "lines": 40567,
  "words": 163123
} as const;
